-- Versionamento del catalogo per il canale a delta
-- (`docs/development/04-data-layer.md` di coachly-fe: `GET /catalog/delta?since=N`).
--
-- L'orologio e' una SEQUENCE, non `updated_at`. Tre ragioni:
--   1. il contratto col client chiede un intero monotono, non un istante;
--   2. i timestamp collidono fra righe scritte nello stesso momento e possono
--      tornare indietro (skew, restore), e un watermark che torna indietro fa
--      riscaricare o — peggio — saltare righe;
--   3. dieci delle ventidue tabelle del catalogo non hanno `updated_at`, e sono
--      proprio le tabelle ponte, cioe' quelle che fanno cambiare le relazioni.
--
-- Lo stamp lo fanno i trigger e non il codice applicativo: il catalogo si
-- scrive anche via SQL (esiste uno schema `exercises_staging`), e un import che
-- non passa dal servizio non chiamerebbe mai il codice. Un trigger non si
-- aggira.
--
-- Additivo e idempotente: si puo' rieseguire, e rieseguirlo copre anche le
-- tabelle aggiunte al catalogo dopo la prima applicazione.

CREATE SEQUENCE IF NOT EXISTS exercises.catalog_version;

-- Le cancellazioni non lasciano traccia nelle tabelle: senza questo registro
-- un client non puo' sapere che una riga e' sparita, e si terrebbe per sempre
-- un esercizio ritirato.
CREATE TABLE IF NOT EXISTS exercises.catalog_tombstone
(
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  text        NOT NULL,
    -- Chiave dell'entita' come oggetto JSON: nove tabelle su ventidue hanno
    -- una primary key composta, e una colonna `entity_id` singola non
    -- basterebbe a rappresentarle.
    entity_key  jsonb       NOT NULL,
    row_version bigint      NOT NULL DEFAULT nextval('exercises.catalog_version'),
    deleted_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS catalog_tombstone_version_idx
    ON exercises.catalog_tombstone (row_version);

-- Ogni UPDATE avanza la versione della riga. L'INSERT e' gia' coperto dal
-- DEFAULT della colonna.
CREATE OR REPLACE FUNCTION exercises.stamp_catalog_version()
    RETURNS trigger
    LANGUAGE plpgsql
AS
$$
BEGIN
    NEW.row_version := nextval('exercises.catalog_version');
    RETURN NEW;
END;
$$;

-- Registra la cancellazione. Le colonne della primary key arrivano come
-- argomenti del trigger, cosi' la funzione resta una sola per tutte le tabelle.
CREATE OR REPLACE FUNCTION exercises.record_catalog_tombstone()
    RETURNS trigger
    LANGUAGE plpgsql
AS
$$
DECLARE
    full_row   jsonb := to_jsonb(OLD);
    entity_key jsonb := '{}'::jsonb;
    key_column text;
BEGIN
    FOREACH key_column IN ARRAY TG_ARGV
        LOOP
            entity_key := entity_key || jsonb_build_object(key_column, full_row -> key_column);
        END LOOP;

    INSERT INTO exercises.catalog_tombstone (table_name, entity_key)
    VALUES (TG_TABLE_NAME, entity_key);

    RETURN OLD;
END;
$$;

-- Applica colonna, indice e trigger a ogni tabella del catalogo.
DO
$$
    DECLARE
        target     record;
        key_list   text;
        trigger_ok boolean;
    BEGIN
        FOR target IN
            SELECT c.relname                                        AS table_name,
                   array_agg(a.attname ORDER BY k.ord)              AS key_columns
            FROM pg_constraint con
                     JOIN pg_class c ON c.oid = con.conrelid
                     JOIN pg_namespace n ON n.oid = c.relnamespace
                     JOIN LATERAL unnest(con.conkey) WITH ORDINALITY AS k(attnum, ord) ON true
                     JOIN pg_attribute a ON a.attrelid = c.oid AND a.attnum = k.attnum
            WHERE n.nspname = 'exercises'
              AND con.contype = 'p'
              AND c.relname <> 'catalog_tombstone'
            GROUP BY c.relname
            ORDER BY c.relname
            LOOP
                EXECUTE format(
                        'ALTER TABLE exercises.%I ADD COLUMN IF NOT EXISTS row_version bigint NOT NULL DEFAULT nextval(''exercises.catalog_version'')',
                        target.table_name);

                EXECUTE format(
                        'CREATE INDEX IF NOT EXISTS %I ON exercises.%I (row_version)',
                        target.table_name || '_row_version_idx', target.table_name);

                EXECUTE format(
                        'DROP TRIGGER IF EXISTS %I ON exercises.%I',
                        target.table_name || '_stamp_version', target.table_name);
                EXECUTE format(
                        'CREATE TRIGGER %I BEFORE UPDATE ON exercises.%I FOR EACH ROW EXECUTE FUNCTION exercises.stamp_catalog_version()',
                        target.table_name || '_stamp_version', target.table_name);

                SELECT string_agg(quote_literal(col), ', ')
                INTO key_list
                FROM unnest(target.key_columns) AS col;

                EXECUTE format(
                        'DROP TRIGGER IF EXISTS %I ON exercises.%I',
                        target.table_name || '_tombstone', target.table_name);
                EXECUTE format(
                        'CREATE TRIGGER %I AFTER DELETE ON exercises.%I FOR EACH ROW EXECUTE FUNCTION exercises.record_catalog_tombstone(%s)',
                        target.table_name || '_tombstone', target.table_name, key_list);

                RAISE NOTICE 'catalog versioning applied to exercises.%', target.table_name;
            END LOOP;
    END
$$;
